stages:
  - test
  - build

include:
  - template: Security/SAST.gitlab-ci.yml

before_script:
  - apt-get update -qy
  - apt-get install -y docker.io

build:
  stage: build
  script:
    - chmod +x build.sh  # Ensure the script is executable
    - ./build.sh

