version: '3'

services:
  caddy:
    image: caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - web

  nginx:
    image: nginx
    expose:
      - "80"
    volumes:
      - ./app/public:/usr/share/nginx/html
    networks:
      - web

networks:
  web:

