name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Run build.sh
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Create ZIP archive
      run: zip -r app.zip app

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: app.zip
